### ISSUE TITLE
Error: Not Authorized (WiGLE.net)

### ISSUE THREAD

**Issue by samxplogs** [e-m3din4/wigle-bt#1]
Hello e-m3din4,

thanks for sharing but I am stuck somehow.
Could you help me? 

I have updated the json file with my API using both:
- Encoded for use: 
-API Token: 

Unfortunately they both failed and and I am not able to query any BLE mac addresses. I have this error.

Error: Not Authorized (WiGLE.net)

Thanks for your help,
Sam

**Comment by e-m3din4** [comment]
it seems your api token isnt correct, you can verify on wigle documentation which are the error throw by API and the one you described maybe be due to not using the token encoded which is also obtained at wigle, or the other easy path, but there is always a chance: a typo, also... is it config.json still named that way and storaged at the same directory with the script? script will looke for the token in that manner.

**Comment by e-m3din4** [comment]
wait, you said both? what do you mean? you just need the string offered by wigle already encoded, it is labeled: api key auth.
